services:

  gateway:
    ports:
      - "80:80"
      - "443:443"

  auth:
    image: ghcr.io/ton-org/auth-service:1.0.0
    environment:
      NODE_ENV: production

  postgres:
    ports: []

  minio:
    ports: []

  grafana:
    ports: []
